
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hub.smaitic.com
  resources:
  - connectionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.smaitic.com
  resources:
  - connectionsets/finalizers
  verbs:
  - update
- apiGroups:
  - hub.smaitic.com
  resources:
  - connectionsets/status
  verbs:
  - get
  - patch
  - update
